version: '3.8'
services:
  
  hello-world:
    image: dockerbogo/docker-nginx-hello-world
    deploy:
      mode: global
      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"
        traefik.http.routers.hello-world.rule: "Host(`hello-world.abc.nfweb.ca`,`hello-world.abc01.nfweb.ca`)"
        traefik.http.routers.hello-world.entrypoints: "websecure"
        traefik.http.routers.hello-world.tls.certresolver: "digitalocean"
        traefik.http.services.hello-world.loadbalancer.server.port: "443"
        traefik.http.services.hello-world.loadbalancer.server.scheme: "https"

    networks:
      - proxy

    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443

networks:
  proxy:
    name: proxy
    driver: overlay
    external: true
