version: '3.8'
services:
# : { } [ ] , & * ? | - < > = ! % @ \

  workspace:
    image: nonfiction/workspace:latest
    hostname: __SWARM__
    restart: unless-stopped

    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"
        
        traefik.http.services.workspace.loadbalancer.server.port: "80"
        traefik.http.services.workspace.loadbalancer.server.scheme: "http"

        traefik.http.routers.workspace.rule: "Host(__HOSTS__)"
        traefik.http.routers.workspace.entrypoints: "websecure"
        traefik.http.routers.workspace.tls.certresolver: "digitalocean"

    volumes:
      - "/work/cache:/cache"
      - "/work/data:/data"
      - "/work:/work"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/root/platform"

    secrets:
      - root_private_key
      - root_password
      - do_auth_token

    networks:
      - proxy

    ports:
      - target: 2222
        published: 2222
        mode: host
      - target: 60000
        published: 60000
        protocol: udp
        mode: host
      - target: 60001
        published: 60001
        protocol: udp
        mode: host
      - target: 60002
        published: 60002
        protocol: udp
        mode: host
      - target: 60003
        published: 60004
        protocol: udp
        mode: host
      - target: 60005
        published: 60005
        protocol: udp
        mode: host
      - target: 60006
        published: 60006
        protocol: udp
        mode: host
      - target: 60007
        published: 60007
        protocol: udp
        mode: host
      - target: 60008
        published: 60008
        protocol: udp
        mode: host
      - target: 60009
        published: 60009
        protocol: udp
        mode: host

    logging:
      options:
        max-size: "1m"

secrets:
  root_private_key:
    external: true
  root_password:
    external: true
  do_auth_token:
    external: true

networks:
  proxy:
    name: proxy
    driver: overlay
    external: true
