version: '3.8'
services:

  <%= $(bin/get app) %>:
    image: nonfiction/caddy:v1

    deploy:
      # mode: global
      mode: replicated
      replicas: <%= $(bin/get nodes_count 2) %>

      restart_policy:
        condition: on-failure

    networks:
      - proxy

    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443

    logging:
      options:
        max-size: "1m"

    volumes:
      - /data/platform/<%= $(bin/get app) %>/Caddyfile:/etc/caddy/Caddyfile
      - /data/platform/<%= $(bin/get app) %>/data:/data
      - /data/platform/<%= $(bin/get app) %>/config:/config

networks:
  proxy:
    name: proxy
    driver: overlay
    attachable: true
