version: '3.8'
services:
  
  hello-world:
    image: nonfiction/hello-world

    deploy:
      mode: global
      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"
        
        traefik.http.services.hello-world.loadbalancer.server.port: "80"
        traefik.http.services.hello-world.loadbalancer.server.scheme: "http"

        traefik.http.routers.hello-world.rule: "Host(__HOSTS__)"
        traefik.http.routers.hello-world.entrypoints: "websecure"
        traefik.http.routers.hello-world.tls.certresolver: "digitalocean"

    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: overlay
    external: true
