version: '3.8'
services:
# : { } [ ] , & * ? | - < > = ! % @ \

  workspace:
    image: nonfiction/workspace:latest
    hostname: __SWARM__

    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]

      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"

        traefik.http.services.workspace.loadbalancer.server.port: "8443"
        traefik.http.services.workspace.loadbalancer.server.scheme: "https"

        traefik.http.routers.workspace.rule: "Host(__HOSTS__)"
        traefik.http.routers.workspace.entrypoints: "websecure"
        traefik.http.routers.workspace.tls.certresolver: "digitalocean"

    volumes:
      - "/work:/work"
      - "/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

    secrets:
      - basicauth_password
      - basicauth_user
      - code_password
      - db_host
      - db_password
      - db_port
      - db_user
      - do_auth_token
      - droplet_image
      - fs_type
      - git_user_email
      - git_user_name
      - github_token
      - github_user
      - region
      - root_password
      - root_private_key
      - sudo_password
      - webhook

    networks:
      - proxy

    ports:
      - target: 2222
        published: 2222
        mode: host
      - target: 60000
        published: 60000
        protocol: udp
        mode: host
      - target: 60001
        published: 60001
        protocol: udp
        mode: host
      - target: 60002
        published: 60002
        protocol: udp
        mode: host
      - target: 60003
        published: 60004
        protocol: udp
        mode: host
      - target: 60005
        published: 60005
        protocol: udp
        mode: host
      - target: 60006
        published: 60006
        protocol: udp
        mode: host
      - target: 60007
        published: 60007
        protocol: udp
        mode: host
      - target: 60008
        published: 60008
        protocol: udp
        mode: host
      - target: 60009
        published: 60009
        protocol: udp
        mode: host

    logging:
      options:
        max-size: "1m"

secrets:
  basicauth_password:
    external: true
  basicauth_user:
    external: true
  code_password:
    external: true
  db_host:
    external: true
  db_password:
    external: true
  db_port:
    external: true
  db_user:
    external: true
  do_auth_token:
    external: true
  droplet_image:
    external: true
  fs_type:
    external: true
  git_user_email:
    external: true
  git_user_name:
    external: true
  github_token:
    external: true
  github_user:
    external: true
  region:
    external: true
  root_password:
    external: true
  root_private_key:
    external: true
  sudo_password:
    external: true
  webhook:
    external: true

networks:
  proxy:
    name: proxy
    driver: overlay
    external: true
