version: '3.8'
services:
# : { } [ ] , & * ? | - < > = ! % @ \

  workspace:
    image: nonfiction/workspace:latest
    hostname: __SWARM__

    deploy:
      mode: replicated
      replicas: 1
      placement:

      restart_policy:
        condition: on-failure

      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"

        traefik.http.services.workspace.loadbalancer.server.port: "8443"
        traefik.http.services.workspace.loadbalancer.server.scheme: "https"

        traefik.http.routers.workspace.rule: "Host(__HOSTS__)"
        traefik.http.routers.workspace.entrypoints: "websecure"
        traefik.http.routers.workspace.tls.certresolver: "digitalocean"

    volumes:
      - /work:/work
      - /data:/data
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      DO_AUTH_TOKEN: "__DO_AUTH_TOKEN__"
      WEBHOOK: "__WEBHOOK__"
      DROPLET_IMAGE: "__DROPLET_IMAGE__"
      FS_TYPE: "__FS_TYPE__"
      REGION: "__REGION__"
      CODE_PASSWORD: "__CODE_PASSWORD__"
      SUDO_PASSWORD: "__SUDO_PASSWORD__"
      BASICAUTH_PASSWORD: "__BASICAUTH_PASSWORD__"
      BASICAUTH_USER: "__BASICAUTH_USER__"
      DB_HOST: "__DB_HOST__"
      DB_PASSWORD: "__DB_PASSWORD__"
      DB_PORT: "__DB_PORT__"
      DB_USER: "__DB_USER__"
      GITHUB_TOKEN: "__GITHUB_TOKEN__"
      GITHUB_USER: "__GITHUB_USER__"
      GIT_USER_EMAIL: "__GIT_USER_EMAIL__"
      GIT_USER_NAME: "__GIT_USER_NAME__"
      ROOT_PASSWORD: "__ROOT_PASSWORD__"
      ROOT_PRIVATE_KEY: "__ROOT_PRIVATE_KEY__"

    networks:
      - proxy

    ports:
      - target: 2222
        published: 2222
        mode: host
      - target: 60000
        published: 60000
        protocol: udp
        mode: host
      - target: 60001
        published: 60001
        protocol: udp
        mode: host
      - target: 60002
        published: 60002
        protocol: udp
        mode: host
      - target: 60003
        published: 60004
        protocol: udp
        mode: host
      - target: 60005
        published: 60005
        protocol: udp
        mode: host
      - target: 60006
        published: 60006
        protocol: udp
        mode: host
      - target: 60007
        published: 60007
        protocol: udp
        mode: host
      - target: 60008
        published: 60008
        protocol: udp
        mode: host
      - target: 60009
        published: 60009
        protocol: udp
        mode: host

    logging:
      options:
        max-size: "1m"

networks:
  proxy:
    name: proxy
    driver: overlay
    external: true
