version: '3.8'
services:

  traefik:
    image: traefik:v2.4.8
    command:

      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Enable Docker Swarm mode
      - --providers.docker.swarmmode
      # - --providers.docker.endpoint=tcp://127.0.0.1:2375
      # - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.endPoint=http://primary:2375

      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false

      # Use this docker network for container communications
      - --providers.docker.network=proxy

      # Enable the access log, with HTTP requests
      # - --accesslog

      # Enable the Traefik log, for configurations and errors
      - --log

      # Enable the Dashboard and API
      - --api
      - --api.insecure
      - --pilot.dashboard=false

      # Allow backend services to serve https with self-signed certs
      - --serversTransport.insecureSkipVerify=true

      # Create a entrypoints http/https listening on ports 80/443
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # Support auto-renewing https certificates
      - --certificatesResolvers.digitalocean.acme.dnsChallenge=true
      - --certificatesResolvers.digitalocean.acme.dnsChallenge.provider=digitalocean
      - --certificatesresolvers.digitalocean.acme.email=dns@nonfiction.ca
      - --certificatesresolvers.digitalocean.acme.storage=/acme.json
      - --certificatesResolvers.digitalocean.acme.dnsChallenge.resolvers=1.1.1.1:53,8.8.8.8:53
      - --certificatesresolvers.digitalocean.acme.dnschallenge.delaybeforecheck=0

      # - --providers.file.directory=/root/docker-host/config
      # - --providers.file.watch=true
      
    deploy:
      mode: global

      # placement:
      #   constraints:
      #     - node.role == manager

      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"

        # Domains Certificates
        traefik.http.routers.wildcard-certs.tls.certresolver: "digitalocean" # __DOMAINS__
        # traefik.http.routers.wildcard-certs.tls.domains[0].main: "example.nfweb.ca"
        # traefik.http.routers.wildcard-certs.tls.domains[0].sans: "*.example.nfweb.ca"

        # Dashboards
        traefik.http.routers.traefik.rule: "Host(__DASHBOARDS__)"
        traefik.http.routers.traefik.entrypoints: "websecure"
        traefik.http.routers.traefik.tls: "true"
        traefik.http.routers.traefik.service: "api@internal"
        traefik.http.services.traefik.loadbalancer.server.port: "8080"
        # traefik.http.services.traefik.loadbalancer.server.port: "888"

        # # Global redirect to https
        # traefik.http.routers.http-catchall.rule: "hostregexp(`{host:.+}`)"
        # traefik.http.routers.http-catchall.entrypoints: "web"
        # traefik.http.routers.http-catchall.middlewares: "redirect-to-https@docker"
        # traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: "https"

    environment:
      DO_AUTH_TOKEN: "__DO_AUTH_TOKEN__"

    networks:
      - proxy
      - docker

    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host

    logging:
      options:
        max-size: "1m"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/data/traefik/acme.json:/acme.json"

# https://github.com/Tecnativa/docker-socket-proxy
  dockersocket:
    image: tecnativa/docker-socket-proxy
    privileged: true
    networks:
      - docker
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
    environment:
      CONTAINERS: 1
      NETWORKS: 1
      POST: 1
      SERVICES: 1
      SWARM: 1
      TASKS: 1
      NODES: 1
    ports:
      - protocol: tcp
        published: 2375
        target: 2375      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      options:
        max-size: "1m"

networks:
  proxy:
    name: proxy
    driver: overlay
  docker:
    name: docker
    driver: overlay
    driver_opts:
      encrypted: 'true'
