version: '3.8'
services:
  
  srv:
    image: nonfiction/hello-world:latest

    deploy:
      mode: global
      labels:
        traefik.enable: "true"
        traefik.docker.network: "proxy"

        traefik.http.services.yoohoo.loadbalancer.server.port: "80"
        traefik.http.services.yoohoo.loadbalancer.server.scheme: "http"
        
        traefik.http.routers.yoohoo.rule: "Host(`yoohoo.suderman.nfweb.ca`)"
        traefik.http.routers.yoohoo.entrypoints: "websecure"
        traefik.http.routers.yoohoo.tls.certresolver: "digitalocean"

    networks:
      - proxy

networks:
  proxy:
    name: proxy
    driver: overlay
    external: true
